//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kost_SiguraGura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamar
    {
        public Kamar()
        {
            this.Pemesanan = new HashSet<Pemesanan>();
            this.Review = new HashSet<Review>();
        }
    
        public long id { get; set; }
        public string nomor_kamar { get; set; }
        public string tipe_kamar { get; set; }
        public string fasilitas { get; set; }
        public decimal harga_per_bulan { get; set; }
        public string status { get; set; }
        public int capacity { get; set; }
        public int floor { get; set; }
        public string size { get; set; }
        public int bedrooms { get; set; }
        public int bathrooms { get; set; }
        public string description { get; set; }
        public string image_url { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime update_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual ICollection<Pemesanan> Pemesanan { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}
