//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kost_SiguraGura
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kost_RahmatEntities1 : DbContext
    {
        public Kost_RahmatEntities1()
            : base("name=Kost_RahmatEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gallery> Gallery { get; set; }
        public DbSet<Kamar> Kamar { get; set; }
        public DbSet<Laporan> Laporan { get; set; }
        public DbSet<PaymentReminder> PaymentReminder { get; set; }
        public DbSet<Pembayaran> Pembayaran { get; set; }
        public DbSet<Pemesanan> Pemesanan { get; set; }
        public DbSet<Penyewa> Penyewa { get; set; }
        public DbSet<Review> Review { get; set; }
        public DbSet<User> User { get; set; }
    }
}
