//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kost_SiguraGura
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReminder
    {
        public long id { get; set; }
        public long pembayaran_id { get; set; }
        public decimal jumlah_bayar { get; set; }
        public System.DateTime tanggal_reminder { get; set; }
        public string status_reminder { get; set; }
        public bool is_sent { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime update_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual Pembayaran Pembayaran { get; set; }
    }
}
