//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kost_SiguraGura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pembayaran
    {
        public Pembayaran()
        {
            this.PaymentReminder = new HashSet<PaymentReminder>();
        }
    
        public long id { get; set; }
        public long pemesanan_id { get; set; }
        public decimal jumlah_bayar { get; set; }
        public System.DateTime tanggal_bayar { get; set; }
        public string bukti_transfer { get; set; }
        public string status_pembayaran { get; set; }
        public string order_id { get; set; }
        public string snap_token { get; set; }
        public string metode_pembyaran { get; set; }
        public string tipe_pembayaran { get; set; }
        public decimal jumlah_dp { get; set; }
        public System.DateTime tanggal_jatuh_tempo { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime update_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual ICollection<PaymentReminder> PaymentReminder { get; set; }
        public virtual Pemesanan Pemesanan { get; set; }
    }
}
