//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kost_SiguraGura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penyewa
    {
        public Penyewa()
        {
            this.Pemesanan = new HashSet<Pemesanan>();
        }
    
        public long id { get; set; }
        public long user_id { get; set; }
        public string nama_lengkap { get; set; }
        public string email { get; set; }
        public string nik { get; set; }
        public string nomor_hp { get; set; }
        public System.DateTime tanggal_lahir { get; set; }
        public string alamat_asal { get; set; }
        public string jenis_kelamin { get; set; }
        public string foto_profil { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime update_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual ICollection<Pemesanan> Pemesanan { get; set; }
        public virtual User User { get; set; }
    }
}
