//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kost_SiguraGura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public long kamar_id { get; set; }
        public decimal rating { get; set; }
        public string comment { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime update_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual Kamar Kamar { get; set; }
        public virtual User User { get; set; }
    }
}
