//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kost_SiguraGura
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Penyewa = new HashSet<Penyewa>();
            this.Review = new HashSet<Review>();
        }
    
        public long id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime update_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string reset_token { get; set; }
        public Nullable<System.DateTime> reset_token_expiry { get; set; }
    
        public virtual ICollection<Penyewa> Penyewa { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}
